"""Codex OAuth 2.0 + PKCE flow.

Starts a temporary TCP server on port 1455 (required by the Codex OAuth
registration) to catch the browser redirect callback, exchanges the
authorization code for tokens, and writes them to secrets/codex.env.
"""
from __future__ import annotations

import asyncio
import base64
import hashlib
import os
import secrets
import time
from pathlib import Path
from urllib.parse import parse_qs, urlparse

import httpx

CODEX_CLIENT_ID    = "app_EMoamEEZ73f0CkXaXp7hrann"
CODEX_AUTH_URL     = "https://auth.openai.com/oauth/authorize"
CODEX_TOKEN_URL    = "https://auth.openai.com/oauth/token"
CODEX_REDIRECT_URI = "http://localhost:1455/auth/callback"
CODEX_SCOPES       = "openid profile email offline_access"
CODEX_PORT         = 1455


def _pkce_verifier() -> str:
    return base64.urlsafe_b64encode(os.urandom(32)).rstrip(b"=").decode()


def _pkce_challenge(verifier: str) -> str:
    digest = hashlib.sha256(verifier.encode()).digest()
    return base64.urlsafe_b64encode(digest).rstrip(b"=").decode()


def build_auth_url(challenge: str, state: str) -> str:
    params = "&".join([
        "response_type=code",
        f"client_id={CODEX_CLIENT_ID}",
        f"redirect_uri={CODEX_REDIRECT_URI}",
        f"scope={CODEX_SCOPES.replace(' ', '+')}",
        "codex_cli_simplified_flow=true",
        "id_token_add_organizations=true",
        f"state={state}",
        f"code_challenge={challenge}",
        "code_challenge_method=S256",
    ])
    return f"{CODEX_AUTH_URL}?{params}"


async def exchange_code(code: str, verifier: str, secrets_file: Path) -> dict:
    """Exchange an authorization code for tokens and write secrets/codex.env.

    Returns {"ok": True} or {"error": "..."}.
    """
    import httpx as _httpx
    try:
        async with _httpx.AsyncClient() as http:
            resp = await http.post(CODEX_TOKEN_URL, data={
                "grant_type":    "authorization_code",
                "client_id":     CODEX_CLIENT_ID,
                "code":          code,
                "redirect_uri":  CODEX_REDIRECT_URI,
                "code_verifier": verifier,
            })
            resp.raise_for_status()
            tok = resp.json()
        access = tok.get("access_token")
        if not access:
            return {"error": "No access_token in token response."}
        expiry = int(time.time()) + int(tok.get("expires_in", 3600))
        secrets_file.parent.mkdir(parents=True, exist_ok=True)
        secrets_file.write_text(
            f"access_token={access}\n"
            f"refresh_token={tok.get('refresh_token', '')}\n"
            f"token_expiry={expiry}\n"
        )
        secrets_file.chmod(0o600)
        return {"ok": True}
    except Exception as exc:
        return {"error": str(exc)}


async def run_oauth_flow(
    secrets_file: Path,
    verifier: str | None = None,
    state: str | None = None,
) -> dict:
    """Run the full PKCE flow. Returns {"ok": True, "auth_url": ...} or {"error": ..., "auth_url": ...}.

    If verifier/state are provided (pre-generated by the caller so the auth_url
    can be returned before the flow completes), they are used directly.
    Otherwise new ones are generated internally.

    The auth_url is always included so the caller can display it if the browser
    didn't open (e.g. remote server scenario).
    """
    if verifier is None:
        verifier = _pkce_verifier()
    if state is None:
        state = secrets.token_hex(16)
    challenge = _pkce_challenge(verifier)
    auth_url  = build_auth_url(challenge, state)

    result: dict = {}
    event = asyncio.Event()

    _HTML_OK  = (
        b"HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n"
        b"<!DOCTYPE html><html><body style='font-family:sans-serif;padding:40px;"
        b"background:#1a1a1a;color:#d4d4d4'><h2 style='color:#4ec9b0'>bareclaw</h2>"
        b"<p>Authenticated. You may close this tab.</p></body></html>"
    )
    _HTML_ERR = (
        b"HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n"
        b"<!DOCTYPE html><html><body style='font-family:sans-serif;padding:40px;"
        b"background:#1a1a1a;color:#d4d4d4'><h2 style='color:#f44'>bareclaw</h2>"
        b"<p>Authentication failed. You may close this tab.</p></body></html>"
    )

    async def _handle(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
        try:
            raw = await reader.read(4096)
            request_line = raw.decode(errors="replace").split("\r\n")[0]
            path = request_line.split(" ")[1] if " " in request_line else "/"
            parsed = urlparse(path)
            params = parse_qs(parsed.query)

            if parsed.path != "/auth/callback":
                writer.write(_HTML_ERR)
                await writer.drain()
                writer.close()
                return

            error     = (params.get("error")     or [None])[0]
            code      = (params.get("code")      or [None])[0]
            ret_state = (params.get("state")     or [None])[0]

            if error:
                result["error"] = f"OAuth error: {error}"
                writer.write(_HTML_ERR)
            elif ret_state != state:
                result["error"] = "State mismatch — possible CSRF."
                writer.write(_HTML_ERR)
            elif not code:
                result["error"] = "No authorization code received."
                writer.write(_HTML_ERR)
            else:
                try:
                    async with httpx.AsyncClient() as http:
                        resp = await http.post(CODEX_TOKEN_URL, data={
                            "grant_type":    "authorization_code",
                            "client_id":     CODEX_CLIENT_ID,
                            "code":          code,
                            "redirect_uri":  CODEX_REDIRECT_URI,
                            "code_verifier": verifier,
                        })
                        resp.raise_for_status()
                        tok = resp.json()

                    access = tok.get("access_token")
                    if not access:
                        result["error"] = "No access_token in token response."
                        writer.write(_HTML_ERR)
                    else:
                        expiry = int(time.time()) + int(tok.get("expires_in", 3600))
                        secrets_file.parent.mkdir(parents=True, exist_ok=True)
                        secrets_file.write_text(
                            f"access_token={access}\n"
                            f"refresh_token={tok.get('refresh_token', '')}\n"
                            f"token_expiry={expiry}\n"
                        )
                        secrets_file.chmod(0o600)
                        result["ok"] = True
                        writer.write(_HTML_OK)
                except Exception as exc:
                    result["error"] = str(exc)
                    writer.write(_HTML_ERR)

            await writer.drain()
            writer.close()
        finally:
            event.set()

    try:
        server = await asyncio.start_server(_handle, "127.0.0.1", CODEX_PORT)
    except OSError as exc:
        return {"error": f"Port {CODEX_PORT} already in use: {exc}", "auth_url": auth_url}

    async with server:
        try:
            await asyncio.wait_for(event.wait(), timeout=120)
        except asyncio.TimeoutError:
            result = {"error": "OAuth flow timed out (120s). Use the manual token option below."}

    result["auth_url"] = auth_url
    return result
